### ISSUE TITLE
Basic Ship Movement

### ISSUE THREAD

**Issue by HanifNaOH** [KoloidStudios/salty-green#1]
Up Down = change speed gear(reverse, gear 1, gear 2)
Left, right = rotation

**Comment by HanifNaOH** [comment]
Add Fuel
Add Gear(gear 1, gear 2, Reverse gear)
Add fish capacity(Kg)
Jadiin template biar player bisa beli/upgrade kapal

**Comment by DK0280705** [comment]
Add Note for Ship gear property:
Use speed multiplier for ships.
Divided by backward multiplier and forward multiplier.
Divided by engine based gear and human based gear.

For example:
- Small wooden boat:
Engine: Backward(0.0x), Forward(0.0x)
Human: Backward(1.0x), Forward(1.0x)
- Hybrid fishing boat:
Engine: Backward(0.4x), Forward(1.0x)
Human: Backward(0.3x), Forward(0.3x)

**Comment by HanifNaOH** [comment]
keknya jangan pake rigid, pas kena collision jittering

pas di test world licin banget dah

Where gear?

**Comment by DK0280705** [comment]
RigidBody memberikan interface yang jelas untuk pengaplikasian objek berbasis fisika. CharacterBody bener bener cmn buat karakter 2D. Untuk jitteringnya bisa dijelaskan krn momentum yg koefisiennya 1 (kecepatan datang = kecepatan pantul). Pantulan terjadi karena bentuk kapal yang persegi panjang.

Untuk licin, sepertinya drag forcenya ngebug. Sama belum implementasi wave sama air resistance.

Gotta fix it soon.

**Comment by DK0280705** [comment]
Basic Ship Movement Done
